databases:
  - name: <%= ENV['POSTGRES_DB'] %>
    databaseName: <%= ENV['POSTGRES_DB'] %>
    user: <%= ENV['POSTGRES_USER'] %>

services:
  - type: web
    name: code-descriptor
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: code-descriptor
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
